### ISSUE TITLE
Unable to get Karma working

### ISSUE THREAD

**Issue by zhon** [allan-stewart/react-hogwarts-tdd-kata#14]
I am hoping to get help on this one.

To run karma

`npm run test-karma`

It fails with 

```
ERROR in ./~/karma-chrome-launcher/index.js
Module not found: Error: Cannot resolve module 'fs' in /Users/zhon/dev/react-hogwarts-tdd-kata/node_modules/karma-chrome-launcher
 @ ./~/karma-chrome-launcher/index.js 1:9-22

ERROR in ./~/karma-chrome-launcher/~/which/which.js
Module not found: Error: Cannot resolve module 'fs' in /Users/zhon/dev/react-hogwarts-tdd-kata/node_modules/karma-chrome-launcher/node_modules/which
 @ ./~/karma-chrome-launcher/~/which/which.js 11:9-22
```

I have tried installing `fs`

I have tried including 

```
  node: {
    fs: "empty"
  }
```

I have tried 

```
 noParse: [
      /karma-chrome-launcher/
    ],
```

**Comment by allan-stewart** [comment]
That is really strange. The fs module is built into node.js; it is the file
system module. I can't think of why it wouldn't be found.

**Comment by zhon** [comment]
Karma runs in the browser. What we need to find out is who is requiring it and tell them to stop it.

**Comment by allan-stewart** [comment]
I've tried a couple ways to get karma running, but just can't seem to figure it out. I ran into the same issue you were seeing, then I tried a very different config and just ran into different issues around ES6 (even with babel going). So I'm shifting focus for a little while to get other parts done.

**Comment by zhon** [comment]
Karma is out. `console.log` is in.
