### ISSUE TITLE
Replace should with chai?

### ISSUE THREAD

**Issue by allan-stewart** [allan-stewart/react-hogwarts-tdd-kata#20]
It looks like you're thinking about replacing `should` with `chai`. Is there any particular reason? I'm fine with either; if we want to go with chai then I'd like to make the rest of the replacements.

**Comment by zhon** [comment]
I found it easier to debug with `chai`. Assert allows a message.

I find `expect` to read more clearly.

I was planning on making the changes as the code went into the readme.

**Comment by zhon** [comment]
It is all moved to chai.
