### ISSUE TITLE
Remove or Respond to Warnings

### ISSUE THREAD

**Issue by zhon** [allan-stewart/react-hogwarts-tdd-kata#21]
In section 1.1.3 and 1.2.1, the tests pass but there are some React warnings that are written to the console along with the test results. Probably not a big deal, but a bit annoying.

**Comment by allan-stewart** [comment]
I went over Story 1 again tonight. There is only one of these React warnings remaining. It says:

> Warning: Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child.

But it's only a transitory error; by the time you get to the end of the story, that error is gone. So I think we're good to close this issue.
