### ISSUE TITLE
Create Final github repository

### ISSUE THREAD

**Issue by zhon** [allan-stewart/react-hogwarts-tdd-kata#24]
This repository will have the following
- readme
-  tags for every section (ie., 1.2.1)
- left in the starting state 

https://github.com/zhon/react-hogwarts-tdd-kata-start is a temporary scratch pad for this repository.

**Comment by zhon** [comment]
I will start on this on Monday. I am hoping to have Kay, Justin and Neil run through this before.

Kay will be running through it Monday morning.

**Comment by allan-stewart** [comment]
It looks like we are pretty close now. :smile:

**Comment by zhon** [comment]
Is there anything we can remove to lighten the size put on the USB drive?

**Comment by zhon** [comment]
I have the starting Point here:

https://github.com/zhon/react-hogwarts-tdd-kata

**Comment by zhon** [comment]
I plan on going through the exercise and adding tags for each point (ie., 1.0.1. 2.2.1)

But that will have to wait until tomorrow. I was having trouble with eslint blowing up. I have just removed it from running.

**Comment by zhon** [comment]
Final Repository created:  https://github.com/zhon/react-hogwarts-tdd-kata
