### ISSUE TITLE
Story 3. Fix bug in SortingHat

### ISSUE THREAD

**Issue by zhon** [allan-stewart/react-hogwarts-tdd-kata#25]

**Comment by zhon** [comment]
I have refactored the sorting hat to do the sorting inside WizardActions.

I will be adding the test to Wizard Actions.

**Comment by allan-stewart** [comment]
I went through this tonight and it looks good. I only made one tweak to the narration, and that was just to make it easier to tell where the updated randomization algorithm was supposed to go.

The only other thing I noticed was that the narration says:

> Are there tests for WizardActions? **Yes, but none that deals with the sorting hat.**

But there are a couple tests in that file which do deal with sorting:

``` js
    it('invokes WizardRepository.save', () => {
      mockWizardRepository.expects('get').once().returns({});
      mockWizardRepository.expects('save').once();

      WizardActions.sortIntoHouse();

      mockWizardRepository.verify();
    });

    it("doesn't set house if it is already set", () => {
      mockWizardRepository.expects('get').once().returns({ house: 'Slytherin' });
      mockWizardRepository.expects('save').never();

      WizardActions.sortIntoHouse();

      mockWizardRepository.verify();
    });
```

So maybe that line of narration should read something like: **Yes, but none of them check which house the wizard was sorted into.**

**Comment by zhon** [comment]
Added your text.

**Comment by zhon** [comment]
Finished! :-)
