### ISSUE TITLE
Create Slides

### ISSUE THREAD

**Issue by zhon** [allan-stewart/react-hogwarts-tdd-kata#27]
Title
Who we are?
Explanation of Kata
- Copy/Paste
- Type in all code
- Read narrative guess code
- Read only headings
- Read only Story headings

Overview of React/Alt
Schedule of when we stop and comment
TDD rhythm
- red, green, refactor
- check website 

Acknowledgments
- Jake
- Jim
- Amy
- Kay
- Others

Other stuff?
I usually use 

reveal.js https://github.com/hakimel/reveal.js/

**Comment by zhon** [comment]
Slide are almost finished.

To run them you just load index.html in a browser.

@allan-stewart, It still needs your twitter (and any other contact information you are interested in).

**Comment by allan-stewart** [comment]
The slides look great. I see you found my twitter handle; I just made a small typo fix. Should we add any other credits on the slides, such as Jake Trent? Mike sent us a sponsors slide; should we add that in somewhere?

The only other thing I wonder about is if there should be one more slide on Red Green Refactor. The current slide shows 9 steps which makes it sound complicated. Maybe the first slide on the subject just says something like:
- Red = write a failing test
- Green = make all tests pass
- Refactor = clean up the code while keeping tests green

Totally just last minute suggestions; don't feel compelled to make any changes. I think the slides are good as is.

**Comment by zhon** [comment]
All done except RGR.
