### ISSUE TITLE
Create Thumb Drives with Presentation

### ISSUE THREAD

**Issue by zhon** [allan-stewart/react-hogwarts-tdd-kata#28]
We need Windows, Mac (and Linux) versions of the following:

Node (12.4 works)
Our project zipped up.

**Comment by zhon** [comment]
Hopefully we won't need Window32

**Comment by allan-stewart** [comment]
I just finished copying the Windows version (the `node-v0.12.4-x86.msi` file and a `zip` of the cloned git repo w/ `node_modules` from `npm install`) onto the 5 USB drives you gave me. I'll bring them with me in the morning.
