### ISSUE TITLE
Create build system

### ISSUE THREAD

**Issue by zhon** [allan-stewart/react-hogwarts-tdd-kata#3]
I like to have linting and a build system. Something to watch the filesystem and re-run all the tests.

**Comment by zhon** [comment]
@jaketrent, How do we include `bootstrap.css` into our `webpack` build system?

I have place a version in the `css` directory.

**Comment by jaketrent** [comment]
You can install bootstrap from npm.  Then you'll need the appropriate loaders in webpack.  The chain I would probably choose is less-loader, css-loader, style-loader.  Then you'll need to import the stylesheet from your app.

If you need help, I can provide additional details and/or code.

**Comment by zhon** [comment]
We are not using less. We are probably only using inline styles.

What I am trying to do is include  

`<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">`

into my generated `index.html` file.

**Comment by jaketrent** [comment]
Well, bootstrap src is less.  You can import that, or I believe you can
import a built css version.  If you use the style-loader, you can get style
tags inserted into your head tag.  If you use the extract text plugin, you
can generate a css file, but I don't know how to make the index.html from
html-webpack-plugin include that yet.  I did start looking into that the
other day and decided it was distracting from what I was really trying to
do.  I'll probably pick that flag up again later.

Good luck!

**Comment by zhon** [comment]
Ah, so it really is hard. Lots of people have this in their webpack config:

``` js
module: {
    loaders: commonLoaders.concat([
      { test: /\.css$/, loader: 'style!css' }
```

It is erroring for me and not telling me what I need to do.

I don't know what `style!css` is suppose to mean.

https://github.com/micahlmartin/nuts/blob/master/config/webpack.js

as an example.

**Comment by zhon** [comment]
The current version of `sinon` is not compatible with webpack. Unreleased version 2.0 is suppose to be compatible. Will try that next.

Like I always say, javascript is like the wild, wild west.

**Comment by zhon** [comment]
Additionally, `rewire` is broken and doesn't have a solution yet.

https://github.com/jhnns/rewire-webpack/issues/12
