### ISSUE TITLE
Where do we put (or simulate) json request to the server

### ISSUE THREAD

**Issue by zhon** [allan-stewart/react-hogwarts-tdd-kata#6]
Typically I use the Repository Pattern from DDD. I am not sure if we have the store handle it or have an action or have another class handle. I am leaning toward a `CatalogRepository`

**Comment by allan-stewart** [comment]
`CatalogRepository` seems fine to me. I like what I see in there right now; it seems similar to what was in the angular version (i.e. the catalog is hard-coded in the source code).

I think that actually hitting a server to act on the json would be a nice addition, if we can make it work easily enough. But even so, the repository pattern seems good to me (pretty self-descriptive too).

**Comment by zhon** [comment]
Currently, the repository simulates hitting the server. I think adding a server will be a low priority.
